FROM python:3.9-slim

WORKDIR /app

COPY api/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY api/ .
COPY config/ config/

EXPOSE 5000

CMD ["python", "app.py"]
